name: Publish prerelease

on:
  push:
    branches:
      - main

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci

      # Write the prerelease version using the commit hash
      - run: npm version from-git --no-git-tag-version

      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm publish --tag dev
